// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgLk6nDMxk4v9fCC3uF1W8Fyxn4T_6LVQ',
    appId: '1:625116962592:web:6bdeae883c760242cdc145',
    messagingSenderId: '625116962592',
    projectId: 'yapyap-887d9',
    authDomain: 'yapyap-887d9.firebaseapp.com',
    storageBucket: 'yapyap-887d9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJCy6DeDL5MpzX8tCLpNkmk3yBYpl9bVg',
    appId: '1:625116962592:android:77e62b91bca3c6a9cdc145',
    messagingSenderId: '625116962592',
    projectId: 'yapyap-887d9',
    storageBucket: 'yapyap-887d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-0CuWNSXkpNFBu87n5jz940acvdNt7bU',
    appId: '1:625116962592:ios:fa8f7a9033016720cdc145',
    messagingSenderId: '625116962592',
    projectId: 'yapyap-887d9',
    storageBucket: 'yapyap-887d9.appspot.com',
    iosClientId: '625116962592-pplaidvbfkjq4ek0p4lkgi2h91gbr2cl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-0CuWNSXkpNFBu87n5jz940acvdNt7bU',
    appId: '1:625116962592:ios:fa8f7a9033016720cdc145',
    messagingSenderId: '625116962592',
    projectId: 'yapyap-887d9',
    storageBucket: 'yapyap-887d9.appspot.com',
    iosClientId: '625116962592-pplaidvbfkjq4ek0p4lkgi2h91gbr2cl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatme',
  );
}
